"""Added 'profile_image_path column to User class

Revision ID: 762c026c3be9
Revises: a75f9c10df6e
Create Date: 2023-04-24 01:40:11.647298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762c026c3be9'
down_revision = 'a75f9c10df6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_path',
                            sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image_path')

    # ### end Alembic commands ###
