"""Added description field to Term

Revision ID: a75f9c10df6e
Revises: 352983f52018
Create Date: 2023-04-21 13:12:43.687498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75f9c10df6e'
down_revision = '352983f52018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
