"""Updated User model

Revision ID: d5f0cd780a30
Revises: 9b25288b4aa4
Create Date: 2023-05-02 20:25:56.874206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f0cd780a30'
down_revision = '9b25288b4aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('twitter_username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('twitter_username')
        batch_op.drop_column('website')

    # ### end Alembic commands ###
